-- MySQL Script generated by MySQL Workbench
-- Sat Jul 26 16:37:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_scrap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_scrap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_scrap` DEFAULT CHARACTER SET utf8 ;
USE `db_scrap` ;

-- -----------------------------------------------------
-- Table `db_scrap`.`actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_scrap`.`actors` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_scrap`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_scrap`.`movies` (
  `id` INT NOT NULL,
  `title` VARCHAR(300) NOT NULL,
  `year` INT NULL,
  `rating` DOUBLE NULL,
  `duration` INT NULL,
  `metascore` INT NULL,
  `detail_url` VARCHAR(300) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_scrap`.`movie_actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_scrap`.`movie_actors` (
  `id` INT NOT NULL,
  `create_at` VARCHAR(45) NOT NULL,
  `movies_id` INT NOT NULL,
  `actors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_actors_movies_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_movie_actors_actors1_idx` (`actors_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_actors_movies`
    FOREIGN KEY (`movies_id`)
    REFERENCES `db_scrap`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_actors_actors1`
    FOREIGN KEY (`actors_id`)
    REFERENCES `db_scrap`.`actors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
